---
encouragements:
  - Come on, you got this
  - You are doing great
  - You are getting better
  - That was pretty good
  - Nice! Better next time

insults:
  - What in the mouse forsaken god of VIM was that?!
  - You call that an attempt?
  - Your parents would be disappointed ...
  - That was not even an attempt
    
